
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 10;
  public static final int POWER = 44;
  public static final int MULT = 38;
  public static final int POOL = 20;
  public static final int INTEGER = 48;
  public static final int NOTEQUAL = 29;
  public static final int MIMP = 59;
  public static final int LPAREN = 56;
  public static final int KRAT = 52;
  public static final int MINUS = 37;
  public static final int RPAREN = 57;
  public static final int CHARACTER = 50;
  public static final int AND = 42;
  public static final int NOT = 41;
  public static final int MOREEQUAL = 27;
  public static final int RATIONAL = 7;
  public static final int LESSEQUAL = 26;
  public static final int OR = 43;
  public static final int LESSTHAN = 40;
  public static final int IN = 11;
  public static final int TDEF = 14;
  public static final int COMMA = 53;
  public static final int SEMICOL = 35;
  public static final int FI = 24;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int LOOP = 19;
  public static final int MAIN = 2;
  public static final int IF = 17;
  public static final int DOT = 58;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int KFLOAT = 51;
  public static final int EQUAL = 34;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int ISEQUAL = 28;
  public static final int LCURLY = 30;
  public static final int KCHAR = 4;
  public static final int BREAK = 61;
  public static final int FDEF = 15;
  public static final int TOP = 9;
  public static final int RCURLY = 31;
  public static final int COLON = 47;
  public static final int DICT = 5;
  public static final int ELSE = 18;
  public static final int LSQUARE = 32;
  public static final int READ = 21;
  public static final int QUEST = 60;
  public static final int DCOLON = 46;
  public static final int RSQUARE = 33;
  public static final int MORETHAN = 45;
  public static final int FLOAT = 8;
  public static final int THEN = 54;
  public static final int KBOOL = 3;
  public static final int STRING = 55;
  public static final int LEN = 25;
  public static final int ALIAS = 16;
  public static final int FALSE = 13;
  public static final int PRINT = 22;
  public static final int IDENTIFIER = 49;
  public static final int KINT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "KBOOL",
  "KCHAR",
  "DICT",
  "KINT",
  "RATIONAL",
  "FLOAT",
  "TOP",
  "SEQ",
  "IN",
  "TRUE",
  "FALSE",
  "TDEF",
  "FDEF",
  "ALIAS",
  "IF",
  "ELSE",
  "LOOP",
  "POOL",
  "READ",
  "PRINT",
  "RETURN",
  "FI",
  "LEN",
  "LESSEQUAL",
  "MOREEQUAL",
  "ISEQUAL",
  "NOTEQUAL",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LESSTHAN",
  "NOT",
  "AND",
  "OR",
  "POWER",
  "MORETHAN",
  "DCOLON",
  "COLON",
  "INTEGER",
  "IDENTIFIER",
  "CHARACTER",
  "KFLOAT",
  "KRAT",
  "COMMA",
  "THEN",
  "STRING",
  "LPAREN",
  "RPAREN",
  "DOT",
  "MIMP",
  "QUEST",
  "BREAK"
  };
}

